# Generated by Django 3.0.5 on 2020-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_card_cc_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_code',
        ),
        migrations.AddField(
            model_name='card',
            name='card_pin',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.PositiveIntegerField(),
        ),
    ]
