# Generated by Django 3.0.5 on 2020-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200602_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_pin',
            field=models.CharField(max_length=4),
        ),
    ]
