# Generated by Django 3.0.5 on 2020-06-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200602_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hundred_notes', models.PositiveIntegerField()),
                ('five_hundred_notes', models.PositiveIntegerField()),
                ('two_thousand_notes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('hundred_notes', models.PositiveIntegerField(blank=True, null=True)),
                ('five_hundred_notes', models.PositiveIntegerField(blank=True, null=True)),
                ('two_thousand_notes', models.PositiveIntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.Card')),
            ],
        ),
    ]
