# Generated by Django 3.0.5 on 2020-06-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_atmmachine_cardtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='card_no',
        ),
    ]
