# Generated by Django 3.0.5 on 2020-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20200602_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
